### PR TITLE
docs: add new organisation readme

### PR DESCRIPTION
**Pull request by souravjain540**
adding new organisation readme.

### CODE REVIEW

**Comment by jancurn** [comment]
Thanks for that. Few small comments: please let's add proxy chain, it's one of our most popular repos.

The hyperlinks contain also ":" (e.g. <a href="https://github.com/apify/fingerprint-suite">fingerprint-suite: </a>), pls let's format it correctly.

**Comment by jancurn** [comment]
Also "monetize your dev skills through [Apify Docs](https://docs.apify.com/)" doesn't make much sense, each bullet point should communicate one thing: find ready-made Actors, learn web scraping, build your Actors, publish & monetize them, learn more

**Comment by souravjain540** [comment]
@jancurn done with changes, let me know if it is okay to merge now :)

**Review by jancurn — APPROVED** [review]
Cool, go for it

**Pull request merged**
